### PR TITLE
Fix json loadin

### LINKED ISSUE #21: fix JSON readin in MATLAB2017
our JSON read/write package `jsonlab-1.5` fails in 2017.  This may be fixed in:
https://github.com/fangq/jsonlab

### PR DESCRIPTION
**Pull request by everyday847**
The fundamental issue is that -- when read in from json -- tons of fields become strings rather than char vectors. You can't pass a string to `getappdata`. File this bug under "it's a pain to support a new version of an interpreter every six months."

Anyway, just casting to char fixes the problem. That's not the most beautiful fix, but it'll take a bit more time for me to figure out exactly where in the loadin process I should be actually mutating `loaddata`. Presumably, I'd be recursively iterating over its fields (and their fields, and...) and casting everything I see from string to char.

Resolves #21.

### CODE REVIEW

**Comment by rhiju** [comment]
by the way @everyday847 i think your branch is doing exactly the right fixes to handle JSON *output*, and the fixes on my branch `rhiju/devel` handle fixes for *input*. Perhaps you can cherry-pick from my branch: 

6287eb870f1e32bfe24eedb3477e7f51781736bd
797d0ae911242d2693d84c091a2ccf4b03fec5e2

and test.

Later today (hopefully), I will also be setting up a branch to create unit tests (MATLAB has an apparently nice unit testing framework).

**Comment by everyday847** [comment]
Fabulous, will do.

**Comment by rhiju** [comment]
I have also added unit tests and merged to master. Let's add `JSON input` and `JSON output` blocks to those tests! Not urgent -- let me know if you don't get to it by end of the week and I'll put on my TODO for my current round of ribodraw updates.

**Comment by everyday847** [comment]
I'll for sure get to it by eow, but not eod; at the moment my priorities are Phenix > group meeting Friday.

**Comment by rhiju** [comment]
@everyday847  i discovered that some of these JSON i/o bugs are fixed in the latest github version of JSON. I am closing this PR and creating a new one based on a branch where I have JSON i/o working and a unit test set up.

**Comment by rhiju** [comment]
The replacing pull request is #32!

**Pull request closed without merging**
